generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.postman.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 16 09:00:12 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: api.getpostman.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 16 04:02:05 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: junit.org
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct  3 02:04:52 2026 GMT
  hsts: true
  hsts_max_age: 31536000
domains:
- domain: postman.com
  dnssec: false
  caa:
  - 0 issuewild "letsencrypt.org"
  - 0 issuewild "pki.goog; cansignhttpexchanges=yes"
  - 0 iodef "mailto:security@postman.com"
  - 0 issue "amazon.com"
  - 0 issue "digicert.com"
  - 0 issue "letsencrypt.org"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
- domain: getpostman.com
  dnssec: false
  caa:
  - 0 issue "digicert.com"
  - 0 issue "letsencrypt.org"
  - 0 issue "pki.goog; cansignhttpexchanges=yes"
  - 0 issuewild "amazon.com"
  - 0 issuewild "digicert.com"
  - 0 issuewild "letsencrypt.org"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
